redis:
  image: redis

db:
  image: postgres:9.4
  environment:
    - POSTGRES_HOST_AUTH_METHOD=trust

vote:
  image: voting_app
  ports:
    - 5001:80
  links:
    - redis

worker:
  image: worker-app
  links:
    - db
    - redis

result:
  image: result_app
  ports:
    - 5002:80
  links: 
    - db
